base_cfg: base.yaml
experiment_name: baseline_mixed
# 使用具体天气名称，与数据目录一致
train_weathers: [
  "clearnoon", "clearsunset", "clearnight",
  "softrainnoon", "softrainsunset", "softrainnight",
  "hardrainnoon", "hardrainsunset", "hardrainnight"
]
val_weathers: [
  "clearnoon", "clearsunset", "clearnight",
  "softrainnoon", "softrainsunset", "softrainnight",
  "hardrainnoon", "hardrainsunset", "hardrainnight"
]
use_weather_aug: false
eval_per_weather: true
save_path: ./logs/checkpoints/baseline_mixed.pth
